---
title: "Developing an integrated prognostic score using germline risk variants and RNA expression from primary breast and ovarian cancers for prognostication of survival across subtypes"

site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    df_print: paged
    toc: true
    theme: spacelab
    highlight: textmate
---
<h3> Project Authors: </h3>
Padma Sheila Rajagopal <br>
Yanyu Liang <br>
Alvaro Barbeira <br>
Owen Melia <br>
Jiamao Zheng <br>
Yonglan Zheng <br>
Toshio Yoshimatsu <br>
Dezheng Huo <br>
Guimin Gao <br>
Olufunmilayo I. Olopade <br>
Hae Kyung Im <br>

<p->The manuscript for this project is currently in progress. Methods and manuscript draft are available on request. </p>

<h3> Analysis Roadmap: </h3>
<p>Generation of <a href="https://parajago.github.io/PTRSOTRS/PRS.html">polygenic score (control)</a> and test of performance in breast cancer using Cox proportional hazards</p>

<p>Generation of <a href="https://parajago.github.io/PTRSOTRS/PTRS.html">predicted transcriptomic score</a> and test of performance in breast cancer using Cox proportional hazards</p>

<p>Generation of <a href="https://parajago.github.io/PTRSOTRS/OTRS.html">observed transcriptomic score</a> and test of performance in breast cancer using Cox proportional hazards</p>

<p>Performance of PTRS/OTRS across <a href="https://parajago.github.io/PTRSOTRS/subtype.html">breast cancer subtypes</a></p>

<p>Test of performance across p-value thresholds: <a href="https://liangyy.github.io/tcga-survival/brca_cox.html">link</a></p>

<p>Validation in ovarian cancer: <a href="https://liangyy.github.io/tcga-survival/index.html#3_OV_cohort">link</a></p>

<p>Data (figures and tables used in the manuscript as well as supplementary material) will be made available once the manuscript is complete. 
Functions used throughout the analysis are described and displayed here. </p>
</main>